GEOSPATIAL_FORMATS = ['csv', 'geojson', 'gpkg', 'shp']
TABULAR_FORMATS = ['csv', 'json', 'xml']

CATALOGUE_ROWS = 10
CATALOGUE_SORT = 'score desc'
CATALOGUE_START = 0

DATASTORE_GEOSPATIAL_FORMATS = ['csv', 'geojson', 'shp']
DATASTORE_TABULAR_FORMATS = ['csv', 'json', 'xml']

DOWNLOAD_FORMAT = 'csv'
DOWNLOAD_PROJECTION = '4326'
DOWNLOAD_OFFSET = '0'
DOWNLOAD_LIMIT = '0'

MAX_FIELD_LENGTH = 350
